name: Develop Branch CI

on:
  push:
    branches:
      - develop

jobs:

  test:
    name: CI Testing
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Fetch all branches
      run: |
        git fetch --prune --unshallow
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clean, Build
      run: bash ./gradlew clean assemble --stacktrace
    - name: Lint
      run: bash ./gradlew lint
    - name: Test
      run: bash ./gradlew app:test
    - name: Update SonarQube
      env:
        LOGIN_KEY: ${{ secrets.SONARCLOUD_LOGIN_KEY }}
      run: bash ./gradlew sonarqube -Dsonar.login=$LOGIN_KEY -Dsonar.branch.name=develop --stacktrace --stacktrace
  apk:
      name: Generate APK
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repo
          uses: actions/checkout@v2
          with:
            submodules: 'recursive'
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Build debug APK
          run: bash ./gradlew assembleDebug --stacktrace
        - name: Upload APK
          uses: actions/upload-artifact@v1
          with:
            name: app
            path: app/build/outputs/apk/debug/app-debug.apk
